# Generated by Django 5.0 on 2023-12-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='integralText',
            field=models.CharField(default='', max_length=25555),
        ),
        migrations.AddField(
            model_name='article',
            name='pdfUrl',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='reference',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='samary',
            field=models.CharField(default='', max_length=25555),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='institutions',
            field=models.CharField(default='', max_length=255),
        ),
    ]
